### ISSUE TITLE
Nucleotide sequences in the pos_skipped_exon file not in the pos_SE_transcripts file

### ISSUE THREAD

**Issue by robertfisher002** [flemingtonlab/SpliceTools#4]
I may be making the wrong assumptions but I noticed if I search for some of the nucleotide sequences in the pos_skipped_exon file in the pos_SE_transcripts file I am unable to find the inclusion of the nucleotide sequences even though they should be included. I also noticed I am able to find some neg_skipped_exon sequences in the neg_SE_transctripts file which doesn't seem to make sense if these are skipped sequences. Am I missing something here? Also, I assume the rmats input can affect the directionality of "pos" and "neg" in this case. For instance if control then treatment is used for sample1 and sample 2 then negative IncLevelDiff values would be representative of treatment-induced inclusion. So therefore, for splicetools we would need to do treatemnt then control for the language to align. 

With this, I just want to clarify basically how SpliceTools is generating the nucleotide/peptide sequences with exon inlcusion/skipping. My assumption is that if the exon is included then the exon's nucleotide/peptide sequence is inserted into the transcript's nucleotide/peptide sequence (and vice verse for exon skipping) and then output in the SE_isoforms_All files. Also, how is the specific transcript isoform selected for each gene for this output? Thanks!

**Comment by nungerleider** [comment]
Sorry for the delay.. let me quickly get back to you regarding the directionality for now and we will respond to the other questions later tonight or tomorrow. Yes, the order matters when running rMATS exactly as you stated. Instead of rerunning rMATS, though, you can use an accessory script that we just uploaded that will simply reverse the signs (bin/rMATS_delta_IncDiff_inverter.pl)

**Comment by nungerleider** [comment]
Ok let me know if this helps:

In the 1_nucleotide_sequences directory, SE_transcripts_neg_IncDiff.fa and SE_transcripts_pos_IncDiff.fa list the nucleotide sequences of only the skipped isoforms. For each skipping event, all possible isoforms are listed based on all isoforms listed in the input annotation file.

SKIPPED_EXONs_neg_IncDiff.fa and SKIPPED_EXONs_pos_IncDiff.fa list the nucleotide sequences of the skipped exons.
In the 2_SE_isoforms_all directory, SE_isoforms_all_neg_IncDiff.fa and SE_isoforms_all_pos_IncDiff.fa list the amino acid sequences of only the skipped isoforms. For each skipping event, all possible isoforms are listed based on all isoforms listed in the input annotation file.

The amino acid sequences of the skipped exons are listed in the 5_skipped_exon_protein_sequences directory.

**Comment by robertfisher002** [comment]
Thanks for the quick response and for the script to switch the rmats analysis around. I'm still confused though about why I am unable to find some of the included exon (pos_incdiff) nucleotide sequences in the SE_transcripts_pos_IncDiff list? If these exons are now included then shouldn't they be in the full transcript sequence? Similarly (but opposite), I am able to find some of the skipped exon (negIncdiff) nucleotide sequences in the SE-transcripts_neg_IncDiff list but since these exons are now skipped I feel like they should be excluded from the transcript sequences.

**Comment by nungerleider** [comment]
Hmm..would you be willing to provide the original input file, the command you used, and the output file (if not too big; and refer me to a couple sequences in question)?

**Comment by robertfisher002** [comment]
Yes, can I email them? What is your email? Thanks!

**Comment by nungerleider** [comment]
Great, its nungerle@tulane.edu

**Comment by robertfisher002** [comment]
Just wanted to double-check that everything in the email came through okay. Thanks for the help!

**Comment by nungerleider** [comment]
Hey Robert - I got the email. Sorry for the delay.

Regarding the **positive IncDiff files**, you asked:
 _"I'm still confused though about why I am unable to find some of the included exon (pos_incdiff) nucleotide sequences in the SE_transcripts_pos_IncDiff list? If these exons are now included then shouldn't they be in the full transcript sequence?"_

As we mentioned above:
_"In the 1_nucleotide_sequences directory, SE_transcripts_neg_IncDiff.fa and **SE_transcripts_pos_IncDiff.fa** list the nucleotide sequences of **only the skipped isoforms.**"_

This is because the canonical isoform sequence is already known. 

Regarding the **negative IncDiff files**, you asked:
_"Similarly (but opposite), I am able to find some of the skipped exon (negIncdiff) nucleotide sequences in the SE-transcripts_neg_IncDiff list but since these exons are now skipped I feel like they should be excluded from the transcript sequences."_

It's possible that the isoforms you are referring to have two separate exon skipping events. Each one is listed separately so if you search the sequence of a skipped exon, you will find it in the other listed isoform (which lacks a different exon). 

Your email refered to only the above issue with the positive IncDiff files. If you think the above statement does not describe what you are seeing, could you send along an example from that file of an exon that shouldn't be in a transcript but is?

Best,
Nate

**Comment by robertfisher002** [comment]
Thanks! 
1. So to clarify, you just remove the exon sequence from each MANE transcript sequence to generate the list of skipped isoforms? 
2. You were right about the neg IncDiff files. Seems like it's becuase they are elsewhere in other transcripts which makes sense.

**Comment by nungerleider** [comment]
Yes, that's right. 

Good luck with everything,

Nate

**Comment by robertfisher002** [comment]
Thanks for being super prompt and responsive!
