### ISSUE TITLE
Retained intron file not defined?

### ISSUE THREAD

**Issue by tailana703** [flemingtonlab/SpliceTools#8]
Hello,

First, thank you for the great toolbox to study splicing!

I have a question on RISpliceSiteScoring.pl. For some reason, it throws an error "Retained intron file not defined!" when I try to run:

perl RISpliceSiteScoring.pl -s RI.MATS.JCEC.txt  -g GRCh38.genome.fa -a hg38_1_22_X_Y_M.bed -f 0.0005
There is no problems with RI file and paths are specified.

At the same time, very similar SESpliceSiteScoring.pl appears to work fine. Any suggestions?

Svetlana

**Comment by mbaddoo** [comment]
Hello, Svetlana-

You are welcome!  We are glad that you find the tools useful.  The reason you are met with the error is because when you use retained intron files as input, you must use the '-r' option. The '-s' option is used for skipped exon input files.  So your command should look like this:

"perl RISpliceSiteScoring.pl -r RI.MATS.JCEC.txt -g GRCh38.genome.fa -a hg38_1_22_X_Y_M.bed -f 0.0005"

At your earliest convenience, please give this a try and let me know if it works.  

Best-

Melody

**Comment by tailana703** [comment]
Hello Melody,

Thank you so much! Indeed it worked.

In the result, I encounter some negative splice site scores in both experimental and annotation outputs. I would expect negative scores in experimental samples (as the condition makes splicing "faulty"), but I'm not sure why I have some negative values in annotation.

Thanks again

Svetlana

**Comment by mbaddoo** [comment]
Hello, Svetlana-

Apologies for the delayed reply.  I am glad the command worked.  It is not an error that you see some negative scores in the output for the known RBP knockdowns.  That's just the way the scoring works.  

Thanks so much for using the tools!

Best-

Melody
