### ISSUE TITLE
Use of unitialized value $unique_path in concatenation

### ISSUE THREAD

**Issue by herber4** [flemingtonlab/SpliceTools#9]
Dear Splicetools, 

I am trying to utilize the SpliceCompare script and keep getting met with the following error:

perl SpliceCompare.pl -i ../../comparison -o ../../comparison/output -m 280 -p 1 -f 0.05        

Reading input directory...

Making output directories...

Processing JCEC files...

Use of uninitialized value $unique_path in concatenation (.) or string at SpliceCompare.pl line 149.
couldn't open output file at SpliceCompare.pl line 149.

Is there any way you could help me trouble shoot this?

python v 3.12.4
perl version v5.32.1

Best, 

Austin

**Comment by mbaddoo** [comment]
Hello Austin-

Thanks so much for using SpliceTools and for opening this issue.  

The quickest fix is to make sure that your output directory is not within the input directory.  So your command would look something like this:

perl SpliceCompare.pl -i ../../comparison -o ../../output -m 280 -p 1 -f 0.05

I am working on editing the code so that the the output directory can be within the input directory and will add this new code shortly.  

Until then, please give this a try and let me know if it works. 

Best-

Melody :)

**Comment by mbaddoo** [comment]
Hello again, Austin-

The SpliceCompare scripts have been edited so that the output directory can be contained within the input directory.  

Please use git clone to obtain the new code. 

Thanks again for opening this issue. 

Best-

Melody
